import type { Metadata } from "next";
import { Young_Serif, Raleway, Poppins } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const youngSerif = Young_Serif({
  variable: "--font-young-serif",
  subsets: ["latin"],
  display: "swap",
  weight: ["400"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body
        className={`${raleway.variable} ${youngSerif.variable} antialiased flex flex-col min-h-screen`}
      >
        <div className="w-100vw px-4 py-6">
          <Image
            className="mx-auto"
            src="/ong-gabriel-logo.svg"
            alt="Logo da ONG Gabriel"
            width={180}
            height={38}
            priority
          />
        </div>
        <main className="flex-1 flex flex-col">{children}</main>
        <footer className="flex items-center justify-center p-6">
          <p className="text-sm text-center font-xs text-s-gunmetal-100">
            <span className="font-bold">
              &copy; {new Date().getFullYear()} ONG Gabriel.
            </span>{" "}
            Todos os direitos reservados. Desenvolvido por PopCorns.
          </p>
        </footer>
      </body>
    </html>
  );
}
